machine:
    python:
        version: 3.7.5
jobs:
  build:
#    docker:
#      - image: circleci/python:3.7.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install python libraries
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
          - "venv"
      - run:
          name: Running tests
          command: |
            python3 -m unittest discover
